#!/bin/bash

#---script to compile all of the point dumping utilities and misc utilities

cd volVectorField

cd helicity
   wmake
cd ..

cd UPoints
   wmake
cd ..

cd vorticityPoints
   wmake
cd ..

  if [ "$1" = ext ]
    then
	echo "compiling extends version of yPlus"
	cd yPlus
   	wmake
	cd ..
    else
	echo "compiling OpenCFD version of yPlus"
	cd yPlusCFD
   	wmake
	cd ..
  fi

cd ..

cd volScalarField

cd helicityPoints
   wmake
cd ..

cd enstrophyPoints
   wmake
cd ..

cd epsilonPoints
   wmake
cd ..

cd CPoints
   wmake
cd ..

cd kPoints
   wmake
cd ..

cd nutPoints
   wmake
cd ..

cd QPoints
   wmake
cd ..

cd uprimePoints
   wmake
cd ..

cd yPoints
   wmake 
cd ..

cd ..

cd miscTools

cd postSwak
   wmake
cd ..

cd Bo
   wmake
cd ..

cd ..
#-----end script---
